#PBS -N CuSi7
#PBS -q mps
#PBS -o output.sparc
#PBS -j oe
#PBS -l nodes=1:ppn=30
#PBS -l mem=30gb
#PBS -l walltime=10:00:00
MYPROCS=`wc -l < ${PBS_NODEFILE}`
module purge
module load intel/15.0
module load mvapich2/2.1
module load fftw/3.3.4
module load mkl/11.2

ulimit -s unlimited

cd ${PBS_O_WORKDIR}
echo $PWD
echo "======================================================================="
mpirun -env MV2_ENABLE_AFFINITY=1 -env MV2_CPU_BINDING_POLICY=bunch -np $MYPROCS ../../../lib/sparc -name CuSi7-ONCV-0.2 -log_summary > CuSi7-0.2.log
echo "======================================================================="
