#!/bin/bash
#SBATCH -J SPARC_testsuite
#SBATCH -A gts-phanish6                    # Account name
#SBATCH -p inferno                             # Partition
#SBATCH -N 2 --ntasks-per-node=24
#SBATCH --mem-per-cpu=7G
#SBATCH -t1:00:00
cd $SLURM_SUBMIT_DIR

module reset
module load intel
echo $PWD 



