#PBS -N Cu
#PBS -q mps
#PBS -o output.sparc
#PBS -j oe
#PBS -l nodes=1:ppn=25
#PBS -l mem=25gb
#PBS -l walltime=10:00:00
MYPROCS=`wc -l < ${PBS_NODEFILE}`
module purge
module load intel/15.0
module load mvapich2/2.1
module load fftw/3.3.4
module load mkl/11.2

ulimit -s unlimited

cd ${PBS_O_WORKDIR}
echo $PWD
echo "======================================================================="
mpirun -env MV2_ENABLE_AFFINITY=1 -env MV2_CPU_BINDING_POLICY=bunch -np $MYPROCS ../../../lib/sparc -name Cu4-ONCV-0.4 -log_summary > Cu4-0.4.log
echo "======================================================================="
