#PBS -N test_H2O
#PBS -q mps
#PBS -o output.sparc
#PBS -j oe
#PBS -l nodes=15:ppn=1
##PBS -l nodes=33:intel
#PBS -l mem=1500gb
#PBS -l walltime=10:00:00

#MYPROCS=`wc -l < ${PBS_NODEFILE}`
MYPROCS=1

module purge
module load intel/15.0
module load mvapich2/2.1
module load fftw/3.3.4
module load mkl/11.2

ulimit -s unlimited

cd ${PBS_O_WORKDIR}
echo $PWD
echo "======================================================================="
mpirun -env MV2_ENABLE_AFFINITY=1 -env MV2_CPU_BINDING_POLICY=bunch -np $MYPROCS ../../../lib/sparc -name sprc-calc -log_summary > H2O.log
#mpirun -env MV2_ENABLE_AFFINITY=1 -env MV2_CPU_BINDING_POLICY=bunch -np $MYPROCS valgrind --leak-check=full --track-origins=yes ../../../lib/sparc -name LiH64 -log_summary > LiH64.log
echo "======================================================================="
