#PBS -N test_H2O
#PBS -q hive-interact
#PBS -o output.sparc
#PBS -j oe
#PBS -l nodes=10:ppn=24
#PBS -l pmem=7gb
#PBS -l walltime=1:00:00

MYPROCS=`wc -l < ${PBS_NODEFILE}`
#MYPROCS=$NP_PBS

ulimit -s unlimited

export MV2_ENABLE_AFFINITY=1
export MV2_CPU_BINDING_POLICY=bunch

cd ${PBS_O_WORKDIR}
echo $PWD
echo "======================================================================="
mpirun -np $MYPROCS ../../../lib/sparc -name sprc-calc > H2O.log
#mpirun -env MV2_ENABLE_AFFINITY=1 -env MV2_CPU_BINDING_POLICY=bunch -np $MYPROCS valgrind --leak-check=full --track-origins=yes ../../../lib/sparc -name LiH64 -log_summary > LiH64.log
echo "======================================================================="
