#PBS -N test_Si
#PBS -q hive-interact
#PBS -o output.sparc
#PBS -j oe
#PBS -l nodes=1:ppn=24
#PBS -l pmem=7gb
#PBS -l walltime=1:00:00

MYPROCS=`wc -l < ${PBS_NODEFILE}`
#MYPROCS=40

#module purge
#module load intel/15.0
#module load mvapich2/2.1
#module load fftw/3.3.4
#module load mkl/11.2

ulimit -s unlimited

export MV2_ENABLE_AFFINITY=1 
export MV2_CPU_BINDING_POLICY=bunch 

cd ${PBS_O_WORKDIR}
echo $PWD
echo "======================================================================="

for f in PBE PBEsol RPBE
do
    for system in "O2-spin/O2" "Si/Si8"
    do
        fname=${f}/${system}
        mpirun -np $MYPROCS ../../lib/sparc -name ${fname} > ${fname}.log
    done
done

echo "======================================================================="
