#PBS -N testing_suite
#PBS -o output.sparc
#PBS -j oe
#PBS -q hive-interact
#PBS -l nodes=1:ppn=1
#PBS -l mem=10gb
#PBS -l walltime=1:00:00

MYPROCS=`wc -l < ${PBS_NODEFILE}`
module purge all
module load intel/19.0.3
module load mvapich2/2.3.1
module load gcc-compatibility/8.3.0

ulimit -s unlimited
export MV2_USE_RDMA_CM=1

cd ${PBS_O_WORKDIR}
echo $PWD
module load valgrind
mpirun -np 1 valgrind --leak-check=full --track-origins=yes --suppressions=./../inplace_reduce.supp --log-file=valgrind_out ./../../sparc -name BaTiO3_valgrind -log_summary > BaTiO3_valgrind.log
