#PBS -N test_Si
#PBS -q hive-interact
#PBS -o output.sparc
#PBS -j oe
#PBS -l nodes=2:ppn=24
##PBS -l nodes=33:intel
#PBS -l pmem=1gb
#PBS -l walltime=1:00:00

#MYPROCS=`wc -l < ${PBS_NODEFILE}`
MYPROCS=48

#module purge
#module load intel/15.0
#module load mvapich2/2.1
#module load fftw/3.3.4
#module load mkl/11.2

ulimit -s unlimited

export MV2_ENABLE_AFFINITY=1
export MV2_CPU_BINDING_POLICY=bunch

cd ${PBS_O_WORKDIR}
echo $PWD
echo "======================================================================="
mpirun -np $MYPROCS ../../../../lib/sparc -name Si64 > Si64.log
#mpirun -np $MYPROCS valgrind --leak-check=full --track-origins=yes ../../lib/sparc -name Si64 > Si64.log
echo "======================================================================="
