#PBS -N test_Si
#PBS -q mps
#PBS -o output.sparc
#PBS -j oe
#PBS -l nodes=1:ppn=64
##PBS -l nodes=33:intel
#PBS -l pmem=1gb
#PBS -l walltime=10:00:00

#MYPROCS=`wc -l < ${PBS_NODEFILE}`
MYPROCS=64

module purge
module load intel/15.0
module load mvapich2/2.1
module load fftw/3.3.4
module load mkl/11.2

ulimit -s unlimited

cd ${PBS_O_WORKDIR}
echo $PWD
echo "======================================================================="
mpirun -env MV2_ENABLE_AFFINITY=1 -env MV2_CPU_BINDING_POLICY=bunch -np $MYPROCS ../../../../lib/sparc -name Si64 -log_summary > Si64.log
#mpirun -env MV2_ENABLE_AFFINITY=1 -env MV2_CPU_BINDING_POLICY=bunch -np $MYPROCS valgrind --leak-check=full --track-origins=yes ../../lib/sparc -name Si64 -log_summary > Si64.log
echo "======================================================================="
